# Generated by Django 3.1.4 on 2020-12-15 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gender',
            fields=[
                ('gender_id', models.IntegerField(default=1, primary_key=True, serialize=False, verbose_name='性别id')),
                ('gender_fix', models.CharField(blank=True, db_index=True, max_length=32, unique=True, verbose_name='性别')),
            ],
            options={
                'verbose_name_plural': '英雄性别',
            },
        ),
        migrations.CreateModel(
            name='position',
            fields=[
                ('position_id', models.IntegerField(default=1, primary_key=True, serialize=False, verbose_name='英雄定位id')),
                ('position_name', models.CharField(blank=True, db_index=True, max_length=32, unique=True, verbose_name='定位')),
            ],
            options={
                'verbose_name_plural': '英雄定位',
            },
        ),
        migrations.CreateModel(
            name='hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='英雄姓名')),
                ('name_price', models.IntegerField(verbose_name='英雄价格')),
                ('name_describe', models.TextField(verbose_name='英雄介绍')),
                ('hero_gender', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='hero_gender', to='web_models.gender', verbose_name='英雄性别')),
                ('hero_position', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='hero_position', to='web_models.position', verbose_name='英雄定位')),
            ],
            options={
                'verbose_name_plural': '英雄',
            },
        ),
    ]
